=== ayushmadhogaria/giftvouchersystem/catalog_20048840.xsd
<?xml version="1.0" encoding="UTF-8"?> <!-- xml type declararion-->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"> <!-- defining namespace xs:-->
<xs:element name="versacegiftstore" type="versacegiftstoreType"/> <!-- root element -->
<!-- use of Valetian Blind schema model-->
<!-- optional data are those having minOccurs=0 maxOccurs=1 -->
<!-- simple type= elements just having texts-->
<!-- complex type= elements having elements, string or attributes -->
<xs:complexType name="versacegiftstoreType">
    <xs:sequence>
        <xs:element name="logo"/>
        <xs:element name="store_name" type="xs:string"/>
        <xs:element name="address" type="xs:string"/>
        <xs:element name="motto" type="xs:string"/>
        <xs:element name="information_store" type="xs:string"/>
        <xs:element name="promo" type="xs:string"/>
        <xs:element name="giftcard" type="giftcardType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="brand" type="brandType"/>
        <xs:element name="footer" type="footerType"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="giftcardType">
    <xs:sequence>
        <xs:element name="card" type="cardType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="typeType" use="required"/>
    <xs:attribute name="modeofpayment" type="modeofpaymentType" use="required"/>
</xs:complexType> 

<xs:simpleType name="typeType">  <!-- restriction for type attribute of giftcard-->
    <xs:restriction base="xs:string">
        <xs:enumeration value="Both"/>
        <xs:enumeration value="Physical"/>
        <xs:enumeration value="Digital"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="modeofpaymentType"> <!-- restriction for modeofpayment attribute of giftcard-->
    <xs:restriction base="xs:string">
        <xs:enumeration value="Cash"/>
        <xs:enumeration value="E-wallet"/>
        <xs:enumeration value="Both"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="cardType">
    <xs:sequence>
        <xs:element  name="phcard_general_info" type="phcard_general_infoType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="sp_card_info"  type="sp_card_infoType" minOccurs="0" maxOccurs="1"/> <!-- optional data -->
        <xs:element name="phadd_card_info" type="phadd_card_infoType"  minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="dgcard_info" type="dgcard_infoType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    <xs:attribute name="category" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="phcard_general_infoType">  <!-- genral information about physical card-->
    <xs:sequence>
       <xs:element name="name" type="nameType" minOccurs="0" maxOccurs="unbounded"/>        
       <xs:element name="cardphoto" type="cardphotoType" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element name="accepted_location" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element name="valid_area" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element name="benefit" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="sp_card_infoType">  <!-- information about special card--> <!-- optional data -->
    <xs:sequence>
        <xs:element name="associated_brand" type="xs:string" minOccurs="0" maxOccurs="1"/> <!-- optional data -->
        <xs:element name="original_price" type="original_priceType" minOccurs="0" maxOccurs="1"/> <!-- optional data -->
        <xs:element name="offer_price" type="offer_priceType" minOccurs="0" maxOccurs="1"/> <!-- optional data -->
        <xs:element name="availability" type="xs:string" minOccurs="0" maxOccurs="1"/> <!-- optional data -->
        <xs:element name="promocode" type="xs:string" minOccurs="0" maxOccurs="1"/> <!-- optional data -->
        <xs:element name="spmessage" type="xs:string" minOccurs="0" maxOccurs="1"/> <!-- optional data -->
    </xs:sequence>
</xs:complexType>

<xs:complexType name="phadd_card_infoType"> <!-- additional information about physical card-->
    <xs:sequence>
        <xs:element name="price" type="priceType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="validity" type="validityType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="number_of_users" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="discount" type="discountType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="type" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="dgcard_infoType">   <!-- information about digital card -->
    <xs:sequence>
        <xs:element name="name" type="nameType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="cardphoto" type="cardphotoType" minOccurs="0" maxOccurs="unbounded"/>                          
        <xs:element name="inform" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="code" type="codeType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="validity" type="validityType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="accepted_location" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="price" type="priceType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="number_of_users" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="discount" type="discountType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="benefit" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:attributeGroup name="nameGroup">  <!-- attributeGroup for differnt attribute of name -->
    <xs:attribute name="edition" type="xs:string" use="optional"/>
    <xs:attribute name="voucherType" type="xs:string" use="optional"/>
</xs:attributeGroup>

<xs:complexType name="nameType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attributeGroup ref="nameGroup"></xs:attributeGroup>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:complexType name="cardphotoType">
    <xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="original_priceType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="currency" type="currencyType" use="required"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:complexType name="offer_priceType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="currency" type="currencyType" use="required"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:complexType name="priceType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="currency" type="currencyType" use="required"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:simpleType name="currencyType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Dollar"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="validityType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="format" type="formatType" use="required"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:simpleType name="formatType">  <!-- restriction for format attrubute values-->
    <xs:restriction base="xs:string">
        <xs:enumeration value="DD-MM-YYYY"/>
    </xs:restriction>
</xs:simpleType>


<xs:simpleType name="codeType">   <!-- restriction for codes of digital codes in regex pattern-->
    <xs:restriction base="xs:token">
        <xs:pattern value="[Ver]{3}[A-Za-z]{3}[0-9]{5}"/>
    </xs:restriction>
</xs:simpleType>


<xs:complexType name="discountType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="ratio" type="xs:string" use="optional"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:complexType name="brandType">
    <xs:sequence>
      <xs:element name="partner" type="xs:string" />  
      <xs:element name="dominos" />
      <xs:element name="apple" />
      <xs:element name="adidas" />
      <xs:element name="dunkin" />
      <xs:element name="amazon" />
      <xs:element name="alibaba" />
      <xs:element name="ebay" />
      <xs:element name="walmart" />
    </xs:sequence>
</xs:complexType>

<xs:complexType name="footerType">
    <xs:sequence>
        <xs:element name="reachout_message" type="xs:string"/>
        <xs:element name="contact_details" type="contact_detailsType"/>
        <xs:element name="socialmedia" type="socialmediaType"/>
        <xs:element name="copyright" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="contact_detailsType">
    <xs:sequence>
        <xs:element name="telephone_number" type="xs:string"/>
        <xs:element name="mobile_number" type="xs:string"/>
        <xs:element name="fax" type="xs:string" minOccurs="0"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="socialmediaType">
    <xs:sequence>
        <xs:element name="email" type="emailType" />
        <xs:element name="website_url" type="xs:string" />
        <xs:element name="facebook" type="xs:string" minOccurs="0" maxOccurs="1"/> <!-- optional data -->
        <xs:element name="instagram" type="xs:string" minOccurs="0" maxOccurs="1"/><!-- optional data -->
        <xs:element name="youtube" type="xs:string" minOccurs="0" maxOccurs="1"/><!-- optional data -->
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="emailType">  <!-- restriction for email using the regex pattern-->
    <xs:restriction base="xs:anyURI">
        <xs:maxLength value="250"/>
        <xs:pattern value="[a-zA-Z0-9_\-\.]+[@][a-z]+[\.][a-z]{2,3}"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== ayushmadhogaria/giftvouchersystem/catalog_20048840.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?> <!-- XML declaration-->
<?xml-stylesheet href="catalog_20048840.css" type="text/css"?>  <!-- importing css file to the xml document-->
<!-- 
    Name:Ayush Madhogaria
    London Met ID: 20048840
    College ID: NP01CP4S210127
    Date: 05-05-2022
-->
<!-- root element versacegiftstore-->
<versacegiftstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="catalog_20048840.xsd">  <!-- importing the schema file -->
    <logo/>
    <store_name> Versace GiftCard Store </store_name>
    <address> üìç London, United Kingdom </address>
    <motto> 
        " Our Gift Cards and Your Choices. Perfect combination. "
    </motto>
    <information_store>
        We have tied up with 8 global brands. Get discount on purchase with these eight 
        brands using our different gift cards.
    </information_store>
    <promo> Buy the limited Special Edition Gift Card worth $1000 in $800. Hurry up and get it!!</promo>
    
    <!-- giftCard element-->
    <giftcard type="Both" modeofpayment= "Both">
        <card category="Special"> <!-- Special card both physical and digital payments-->
            <phcard_general_info><!-- element containing general info about special cards -->
               <name edition="SpecEd">Versace Special Edition GiftCard</name>
               <cardphoto name="Special"/>
               <accepted_location> Accepted on: Multiple platforms of all of our partner stores. </accepted_location> 
               <valid_area> Locations: In all the physical branches of the four chain stores all over the globe and the e-commerce sites. </valid_area>
               <benefit>
                   <![CDATA[ Description:
                   You will get upto 20% discounts on all the stores and services of 
                   Dominos, Apple, Adidas, Dunkin, Amazon.com, Alibaba, eBay, Walmart 
                   depending on total amount. Interesting fact about this card is the 
                   only card at Versace GiftStore that ensures discount in both physical 
                   and online stores.]]>
               </benefit>
            </phcard_general_info>
            <sp_card_info>  <!-- element containing info about special cards--><!-- optional data-->
               <associated_brand> Brands Associated: Dominos, Apple, Adidas, Dunkin,Amazon,Walmart,ebay </associated_brand> <!-- optional data-->
               <original_price currency="Dollar"> Actual Price: $1000 </original_price>  <!-- optional data-->
               <offer_price currency="Dollar"> Offer Price: $800 </offer_price>  <!-- optional data-->
               <availability>Remaining cards: Only 60 Special Edition cards are available with us.</availability><!-- optional data-->
               <promocode>Promo Code: VerSpEd22 </promocode> <!-- optional data-->
               <spmessage>This card offers you lifetime membership with us with only $100
                   as the minimal renewal fees per annum.Using promocode above gives you discount 
                   on online purchases while this card will give you discount on physical stores.
               </spmessage> <!-- optional data-->
            </sp_card_info>
        </card>
    </giftcard>
         
    <!-- giftcard element -->
    <giftcard type="Physical" modeofpayment= "Cash" >
        <card category="Premium"><!-- premium category cards-->
            <phcard_general_info><!-- element containing general information about Physical cards -->
               <name edition="PremEd">Premium Edition GiftCard</name>
               <cardphoto name="Premium"/>
               <accepted_location> Accepted on: Multiple physical platforms of our food chain, gadgets and apparels stores. </accepted_location>
               <valid_area>Locations: All the stores of our partners in UK, USA, India, Malaysia, Dubai, HongKong and China. </valid_area>
               <benefit>
                    <![CDATA[ Description:
                    You will get a VIP discount on all the locations of Dominos, 
                    Dunkin, Adidas and Apple stores.The card will have access in almost 7 different countries.
                    Special offers will be notified to you sooner or later. Free Card reload on special occassions. ]]>
                </benefit> 
            </phcard_general_info>
            <phadd_card_info><!-- element containing  Additional information of physical cards -->
               <price currency="Dollar"> Price: $500 </price> <!-- optional data-->
               <validity format="DD-MM-YYYY"> Valid Till: 06-12-2026 </validity>
               <number_of_users> Total number of Users: 1253 </number_of_users>              
               <discount ratio="Percentage"> Estimated Discount: Upto 15% on every purchase depending on total amount </discount>  <!-- Optional DATA-->
               <type>Card Type: Physical (Only accepted on physical purchases in stores). </type><!-- optional-->
            </phadd_card_info>
        </card>

        <card category="Platinum"><!-- platinum category cards-->
            <phcard_general_info><!-- element containing general information about Physical cards -->
               <name edition="PlatEd">Platinum Edition GiftCard</name>
               <cardphoto name="Platinum"/>
               <accepted_location> Accepted on: Multiple physical platforms of our food chains and apparels stores. </accepted_location>
               <valid_area>Locations: All the stores of our partners in UK, USA, India, Malaysia and Dubai. </valid_area> <!-- Optional DATA-->
               <benefit>
                   <![CDATA[ Description:
                   You will get a fair discount on all the locations mentioned.
                   The card will have access in 5 different countries. You will get
                   discounts on  Dominos, Dunkin and Adidas. 
                   Special offers will be offered to you on special occassions.]]>
               </benefit>
            </phcard_general_info>
            <phadd_card_info><!-- element containing additional information about Physical cards  -->
               <price currency="Dollar"> Price: $100 </price>
               <validity format="DD-MM-YYYY"> Valid Till: 06-12-2024 </validity> <!-- Optional DATA-->
               <number_of_users> Total number of Users: 7000 </number_of_users>        <!-- Optional DATA-->
               <discount ratio="Percentage"> Estimated Discount: upto 10% on every purchase depending on total amount</discount>
               <type>Card Type: Physical (Only accepted on physical purchases in stores). </type><!-- optional-->
            </phadd_card_info>
        </card>
    
        <card category="Regular"><!-- regular category cards-->
            <phcard_general_info><!-- element containing general information about Physical card -->
               <name edition="ReguEd">Regular Edition GiftCard</name>
               <cardphoto name="Regular"/>
               <accepted_location> Accepted on: Certain physical platforms of our food chains and clothing stores. </accepted_location>
               <valid_area>Location: Only in the boundary of the United Kingdom.</valid_area>
               <benefit>
                   <![CDATA[ Description:
                   You will get discount in Adidas, Dominos and Dunkin stores. However,
                   this card will have access only within the boundary of United Kingdom only.
                   No special offers will be offered to you except on our birth anniversary.]]>
               </benefit>
            </phcard_general_info>
           <phadd_card_info><!-- element containing additional information about Physical card -->
               <price currency="Dollar"> Price: $50 </price>
               <validity format="DD-MM-YYYY"> Valid Till: 06-12-2022 </validity>
               <number_of_users> Total Number of Users: 5000 </number_of_users>
               <discount ratio="Percentage">5% Discount are available only in weekends on purchases. </discount>
               <type>Card Type: Physical (Only accepted on physical purchases in stores). </type>    <!-- optional-->
           </phadd_card_info>
        </card>
    </giftcard>
    
    <!-- giftcard element-->
    <giftcard type= "Digital" modeofpayment= "E-wallet" >
        <card category="VIP">  <!-- VIP digital card -->
            <dgcard_info><!-- element containing all the information about Digital cards -->
               <name voucherType="VIPDg">VIP Digital Voucher</name>
               <cardphoto name="VIP"/>
               <inform>Point on blurred text for coupon code. </inform>
               <code> VerVIP22092 </code>
               <validity format="DD-MM-YYYY"> Valid Till: 09-12-2030 </validity> <!-- optional data -->
               <accepted_location> Accepted on: Global e-commerce platforms which includes Amazon, Walmart and eBay. </accepted_location>
               <price currency="Dollar"> Price: $500 </price>
               <number_of_users> Number of Users till date: 567 </number_of_users>
               <discount ratio="Percentage"> Estimated discount: upto 20% discount in e-store depending on total amount </discount>
               <benefit>
                   Use gift card coupon code and get heavy discounts. Save more with our vouchers and cards. 
                   Amazon, eBay and Walmart awaits to offer you discounts. 
               </benefit>
            </dgcard_info>
        </card>

        <card category="SpecialDigital"> <!-- Special Digital Card-->
            <dgcard_info><!-- element containing all the information about Digital cards -->
               <name voucherType="SpecDg">Special Digital Voucher</name>
               <cardphoto name="SpecialDg"/>
